# Use an official Haskell image as a base image
FROM haskell:latest

# Install any necessary tools
# RUN apt-get update && apt-get install -y \
#     build-essential \
#     curl

# Set up the working directory
WORKDIR /workspace